name: cyber-attacker-backend
region: sgp
services:
  - name: backend
    github:
      repo: Choeng-Rayu/cyber_project_T1Y3
      branch: main
      deploy_on_push: true
    source_dir: source/Attacker/backend
    http_port: 5000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    run_command: npm start
    envs:
      - key: DB_HOST
        scope: RUN_TIME
        value: coffe-management-db1st-choengrayu307-607c.b.aivencloud.com
      - key: DB_PORT
        scope: RUN_TIME
        value: "21011"
      - key: DB_USER
        scope: RUN_TIME
        value: avnadmin
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: "${DB_PASSWORD}"
      - key: DB_NAME
        scope: RUN_TIME
        value: defaultdb
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "5000"
